-- public."Mails" definition
CREATE TABLE public."Mails" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Subject" varchar(200) NOT NULL,
	"Body" text NOT NULL,
	"SentAt" timestamptz NOT NULL,
	"UserId" int4 NULL,
	"SubscriptionId" int4 NULL,
	CONSTRAINT "PK_Mails" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Mails_SubscriptionId" ON public."Mails" USING btree ("SubscriptionId");
CREATE INDEX "IX_Mails_UserId" ON public."Mails" USING btree ("UserId");

-- public."Operators" definition
CREATE TABLE public."Operators" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"FullName" varchar(100) NOT NULL,
	"Document" varchar(20) NOT NULL,
	"Email" text NOT NULL,
	"Status" varchar(20) NOT NULL,
	"IsActive" bool NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_Operators" PRIMARY KEY ("Id")
);

-- public."Payments" definition
CREATE TABLE public."Payments" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TicketId" int4 NULL,
	"SubscriptionId" int4 NULL,
	"OperatorId" int4 NULL,
	"Amount" numeric(10, 2) NOT NULL,
	"PaymentMethod" varchar(20) NOT NULL,
	"PaymentTime" timestamptz NOT NULL,
	"ReferenceNumber" varchar(50) NULL,
	CONSTRAINT "PK_Payments" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Payments_OperatorId" ON public."Payments" USING btree ("OperatorId");
CREATE INDEX "IX_Payments_SubscriptionId" ON public."Payments" USING btree ("SubscriptionId");
CREATE INDEX "IX_Payments_TicketId" ON public."Payments" USING btree ("TicketId");

-- public."Rates" definition
CREATE TABLE public."Rates" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TypeVehicle" varchar(20) NOT NULL,
	"HourPrice" numeric(10, 2) NOT NULL,
	"AddPrice" numeric(10, 2) NULL,
	"MaxPrice" numeric(10, 2) NULL,
	"GraceTime" int4 NULL,
	"IsActive" bool NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NULL,
	CONSTRAINT "PK_Rates" PRIMARY KEY ("Id")
);

-- public."Shifts" definition
CREATE TABLE public."Shifts" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"OperatorId" int4 NOT NULL,
	"StartTime" timestamptz NOT NULL,
	"EndTime" timestamptz NULL,
	"InitialCash" numeric(10, 2) NULL,
	"FinalCash" numeric(10, 2) NULL,
	"TotalCashPayments" numeric(10, 2) NULL,
	"TotalCardPayments" numeric(10, 2) NULL,
	CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Shifts_OperatorId" ON public."Shifts" USING btree ("OperatorId");

-- public."Subscriptions" definition
CREATE TABLE public."Subscriptions" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" int4 NOT NULL,
	"VehicleId" int4 NOT NULL,
	"StartDate" timestamptz NOT NULL,
	"EndDate" timestamptz NOT NULL,
	"MonthlyPrice" numeric(10, 2) NOT NULL,
	"Status" varchar(20) NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NULL,
	CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Subscriptions_UserId" ON public."Subscriptions" USING btree ("UserId");
CREATE INDEX "IX_Subscriptions_VehicleId" ON public."Subscriptions" USING btree ("VehicleId");

-- public."Tickets" definition
CREATE TABLE public."Tickets" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TicketNumber" varchar(50) NOT NULL,
	"VehicleId" int4 NOT NULL,
	"OperatorId" int4 NULL,
	"SubscriptionId" int4 NULL,
	"RateId" int4 NULL,
	"EntryTime" timestamptz NOT NULL,
	"ExitTime" timestamptz NULL,
	"TotalAmount" numeric(10, 2) NULL,
	"TotalMinutes" int4 NULL,
	"QRCode" text NULL,
	"CreatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Tickets_OperatorId" ON public."Tickets" USING btree ("OperatorId");
CREATE INDEX "IX_Tickets_RateId" ON public."Tickets" USING btree ("RateId");
CREATE INDEX "IX_Tickets_SubscriptionId" ON public."Tickets" USING btree ("SubscriptionId");
CREATE INDEX "IX_Tickets_VehicleId" ON public."Tickets" USING btree ("VehicleId");

-- public."Users" definition
CREATE TABLE public."Users" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"FullName" varchar(100) NOT NULL,
	"Document" varchar(20) NOT NULL,
	"Email" text NOT NULL,
	"Status" varchar(20) NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- public."Vehicles" definition
CREATE TABLE public."Vehicles" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Plate" varchar(20) NOT NULL,
	"Type" varchar(20) NOT NULL,
	"UserId" int4 NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_Vehicles_UserId" ON public."Vehicles" USING btree ("UserId");

-- public."Mails" foreign keys
ALTER TABLE public."Mails" ADD CONSTRAINT "FK_Mails_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES public."Subscriptions"("Id");
ALTER TABLE public."Mails" ADD CONSTRAINT "FK_Mails_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id");

-- public."Payments" foreign keys
ALTER TABLE public."Payments" ADD CONSTRAINT "FK_Payments_Operators_OperatorId" FOREIGN KEY ("OperatorId") REFERENCES public."Operators"("Id") ON DELETE SET NULL;
ALTER TABLE public."Payments" ADD CONSTRAINT "FK_Payments_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES public."Subscriptions"("Id") ON DELETE SET NULL;
ALTER TABLE public."Payments" ADD CONSTRAINT "FK_Payments_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES public."Tickets"("Id") ON DELETE SET NULL;

-- public."Shifts" foreign keys
ALTER TABLE public."Shifts" ADD CONSTRAINT "FK_Shifts_Operators_OperatorId" FOREIGN KEY ("OperatorId") REFERENCES public."Operators"("Id") ON DELETE CASCADE;

-- public."Subscriptions" foreign keys
ALTER TABLE public."Subscriptions" ADD CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;
ALTER TABLE public."Subscriptions" ADD CONSTRAINT "FK_Subscriptions_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES public."Vehicles"("Id") ON DELETE CASCADE;

-- public."Tickets" foreign keys
ALTER TABLE public."Tickets" ADD CONSTRAINT "FK_Tickets_Operators_OperatorId" FOREIGN KEY ("OperatorId") REFERENCES public."Operators"("Id") ON DELETE SET NULL;
ALTER TABLE public."Tickets" ADD CONSTRAINT "FK_Tickets_Rates_RateId" FOREIGN KEY ("RateId") REFERENCES public."Rates"("Id") ON DELETE SET NULL;
ALTER TABLE public."Tickets" ADD CONSTRAINT "FK_Tickets_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES public."Subscriptions"("Id") ON DELETE SET NULL;
ALTER TABLE public."Tickets" ADD CONSTRAINT "FK_Tickets_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES public."Vehicles"("Id") ON DELETE CASCADE;

-- public."Vehicles" foreign keys
ALTER TABLE public."Vehicles" ADD CONSTRAINT "FK_Vehicles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;